### ISSUE TITLE
[Question] The name of the colorscheme

### ISSUE THREAD

**Issue by bitterteasweetorange** [gsuuon/note.nvim#2]
Could you please provide me with the name of the colorscheme?
Thanks!

![image](https://github.com/gsuuon/note.nvim/assets/115888595/e0e66082-ff83-41cb-b25c-3af7f9f08b7b)

**Comment by gsuuon** [comment]
Hi! It's https://github.com/sainnhe/everforest

**Comment by ellisTranProscia** [comment]
Hello, how did you get the highlighting to work?
